# Generated by Django 4.0.4 on 2022-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_featuredimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
