# Generated by Django 4.0.4 on 2022-09-05 16:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_featuredimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.TextField(default=uuid.UUID('d4aa19f5-4116-4634-ad10-88293e6b3527'), unique=True),
        ),
    ]
