# Generated by Django 4.0.4 on 2022-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default='bc3a2cbd-41bc-4631-b6f7-7a4751d3ce15', unique=True),
        ),
    ]
