# Generated by Django 4.0.4 on 2022-09-05 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default=uuid.UUID('cc337072-77f3-4977-8691-31c62aa95e13'), unique=True),
        ),
    ]
