# Generated by Django 4.0.4 on 2022-09-05 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default=uuid.UUID('ae3300b4-826d-4e61-9059-0544ba65f518')),
        ),
    ]
