# Generated by Django 4.0.4 on 2022-09-05 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(default=uuid.UUID('b9165469-6f75-4cdd-b26b-874daf6dd6c7')),
        ),
    ]
